site_title: "Special Forces Training"
site_description: "Allenamento ispirato alle forze speciali per atleti che vogliono il meglio. Preparati come un professionista con programmi specializzati e tecniche d'elite."
logo: "logo.png"

seo:
  keywords: "special forces training, allenamento militare, fitness elite, preparazione fisica, forze speciali italiane, crossfit, HIIT"
  google_analytics: ""
  google_console: ""

email:
  contact_email: "info@specialtrainingfitness.it"
  app_email: "app@specialtrainingfitness.it"
  support_email: "support@specialtrainingfitness.it"
  pdf_url: "https://www.specialtrainingfitness.it/assets/guida.pdf"