name: Deploy to VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to VM
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VM_HOST }}
        username: deploy
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        key_path: ~/.ssh/deploy_key
        script: |
          cd /var/www/specialtrainingfitness.it
          git clone --depth 1 https://github.com/${{ github.repository }}.git temp || true
          cd temp
          cp -r html/* ../html/
          cd ..
          rm -rf temp
          sudo nginx -t && sudo systemctl reload nginx
